### ISSUE TITLE
NEED HLEP: Why need to reopen a link for each local xa transaction?

### ISSUE THREAD

**Issue by jwrookie** [dtm-labs/dtm#334]
https://github.com/dtm-labs/dtm/blob/a788ebe5e83b9f61af44430c1d2a7eb6ffe104da/client/dtmcli/xa.go#L41-L60

**Comment by yedf2** [comment]
@yedf2 another question, i check the code of dtm about xa local transaction, find that the server side has to do sql.Open in every transaction. I think it will cause bad performance. It there any approach i can just pass a connection instead of the DBConf?
https://github.com/dtm-labs/dtm/blob/31bf7d9fad4d0b6a15b5573229053eda5603b745/dtmcli/dtmimp/trans_xa_base.go#L36

_Originally posted by @SgtDaJim in https://github.com/dtm-labs/dtm/issues/277#issuecomment-1106117540_

**Comment by jwrookie** [comment]
got it, thanks for your reply
